sudo: true
language: bash
dist: bionic

before_install:
  - openssl aes-256-cbc -K $encrypted_1c3fee7955db_key -iv $encrypted_1c3fee7955db_iv
    -in deploy_rsa.enc -out deploy_rsa -d
addons:
  ssh_known_hosts:
    - $VPS_HOST
before_deploy:
  - openssl aes-256-cbc -K $encrypted_1c3fee7955db_key -iv $encrypted_1c3fee7955db_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo $TRAVIS_BUILD_DIR
  - echo -e "Host ${VPS_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  script: rsync --quiet -rvz $TRAVIS_BUILD_DIR/ $VPS_USERNAME@$VPS_HOST:$DEPLOY_DIR
  on:
    branch: master
#  - sudo rm -rf /var/lib/apt/lists/*
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
#  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
#  - mkdir -vp ~/.docker/cli-plugins/
#  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
#  - chmod a+x ~/.docker/cli-plugins/docker-buildx

#script:
#  - java --version
#  - docker --version
#  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#  - docker build -t telegram-bot .
#  - docker tag telegram-bot:latest kalpak44/telegram-bot:latest
