sudo: true
language: java
dist: bionic
before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - sudo apt-get install sshpass
script:
  - java --version
  - docker --version
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t telegram-bot .
  - docker tag telegram-bot:latest kalpak44/telegram-bot:latest
  - docker push kalpak44/telegram-bot:latest
  - sshpass -V
  - ssh -v $VPS_HOST
  - sudo sshpass -p $VPS_PASSWORD ssh $VPS_USERNAME@$VPS_HOST
  - docker ps --all
