bot:
  token: token
  username: username
payments:
  stripe:
    success-url: https://vanillacyprus.com/
    cancel-url: https://vanillacyprus.com/
    key:
      public: public_key
      secret: secret